### ISSUE TITLE
Language Support for your Theme

### ISSUE THREAD

**Issue by schmanat** [MunifTanjim/minimo#1]
First of all, thx for this theme.

I love minimalistic websites, is it possible to support other languages? 
I use your theme on my private site and I write post in German, so it would be cool to translate, for example, the Headline "Recent Posts".

**Comment by MunifTanjim** [comment]
@schmanat Of course that is possible. I'll add a template file for translation as soon as I can.

**Comment by schmanat** [comment]
Thx for your quick response. Don't stress 👍

**Comment by MunifTanjim** [comment]
Added it. So you will have to add this to your config file:

```toml
defaultContentLanguage = "en"
[languages]
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
```

For german, replace the `en` with `de`.
And place a `de.toml` file in your site's `/theme/minimo/i18n` folder. Sample translation file can be found on the same folder.
