### ISSUE TITLE
How to set the length of recent_posts widget if theme is installed via git submodule?

### ISSUE THREAD

**Issue by jobanputra** [MunifTanjim/minimo#128]
I need to change the length of the recent_posts widget.  I have looked at this: https://minimo.netlify.com/docs/widgets/#widget-recent-posts but since I've installed the theme via a git submodule I do not have the option to modify the /data/config/widgets.toml config file. 

Is it possible to configure widgets via settings defined in the site's config.toml file? I've tried setting this in config.toml and it does not work.
```toml
[data.config.widgets.recent_posts]
title = "" 
length = 14 
excludeTypes = ["page"] 
```

**Comment by MunifTanjim** [comment]
Create that same directory structure in your site's root repository: `/data/config/widgets.toml`

In simple words, copy `/themes/minimo/data/config/widgets.toml` to `/data/config/widgets.toml`. And modify that instead.

This is how overriding works in Hugo.

ref: https://gohugo.io/themes/customizing/

**Comment by jobanputra** [comment]
Thank you. Your suggestion worked for the recent_posts.length, but the title does not seem to change from **Recent Posts** to the value in my file.

**Comment by MunifTanjim** [comment]
Without taking a look at your settings, I can't say what's causing the problem.

**Comment by jobanputra** [comment]
This is the content of the `/data/config/widgets.toml` file in my repository. The title on the home page still shows **Recent Posts**. Note that I do see **25** posts so I know the settings are being picked up.
```toml
[about]
title = ""
description = ""
logo = "/images/logo.png"

[recent_posts]
title = "My posts"
length = 25
excludeTypes = ["page"]

[sidebar_menu]
title = ""
mirror = ""

[social_menu]
title = ""
platforms = ["github","facebook","twitter","instagram","email","codepen","gitlab","linkedin","telegram","google_scholar"]

[taxonomy_cloud]
title = ""
taxonomy = "tags"
shuffle = false
```
