### ISSUE TITLE
Increase span width of sidebar menu toggler

### ISSUE THREAD

**Issue by pat-s** [MunifTanjim/minimo#191]
Would it be possible to increase the width of the sidebar menu toggler across the respective top-level category name? Maybe with a switch as an `menu.main` argument?

Our main menus do not trigger a new site but are just boxes to keep the sidebar tidy.

Currently, the sub-menus are only toggled when clicking on the "+".

https://mlr-org.com/

**Comment by MunifTanjim** [comment]
Can't promise any update for this, I'm a bit busy for the time being.

But what you're trying to do is possible with minor HTML & CSS modification.

**Comment by pat-s** [comment]
> But what you're trying to do is possible with minor HTML & CSS modification.

Thanks for the quick reply.
I played around a bit but wasn't successful. It's minor ofc but we would highly appreciate it :+1:

**Comment by MunifTanjim** [comment]
Try something like this:

```css
.sidebar-menu .item.has-children {
  position: relative;
}
.sidebar-menu .has-children > a {
  margin-right: 1em;
}
.sub-menu-toggler {
  width: 100%;
  text-align: right;
  background: transparent;
  position: absolute;
  top: 3px;
}
```
