### ISSUE TITLE
Translation of About widget for multilingual site

### ISSUE THREAD

**Issue by solrayc** [MunifTanjim/minimo#207]
Is there a way to translate About Widget configuration to multiple languages that are present on my site?

I tried to play with different variants of ` [languages.rus.about]  ` in config.toml with no luck.

Below is a reference to a related issue:

> FYI @druxstr, I just figured this out myself: You can modify two headers independently or together. Changes to `config.toml` affects both unless you add title and description to `[about]` widget in `widgets.toml`, which only affects the sidebar.
>
> _Originally posted by @GershTri in https://github.com/MunifTanjim/minimo/issues/145#issuecomment-405577968_

**Comment by MunifTanjim** [comment]
You can do that from the **`/data/config/widgets.toml`** file like this:

```toml
[about]
title = ""
description = ""
...
[rus.about]
title = ""
description = ""
...
```

Or if you prefer to do it from the **`/config.toml`** file, you can probably do this (I'm not sure):

```toml
title = ""
...
[params.info]
description = ""
...
[languages.rus]
...
title = ""
...
[languages.rus.info]
description = ""
```

Let me know if that helps...
