### ISSUE TITLE
Alignment question 

### ISSUE THREAD

**Issue by prashanth1k** [MunifTanjim/minimo#239]
Hello. Thanks for the great theme.

I am trying to use some custom CSS and for the life of me cannot figure out two alignment changes - 

1. How can I get the nav menu (at the top) to right-align?
I tried adding justify/align for `nav#main-menu.menu.main-menu' in custom.css, but that always seems to align to left. However, I can do a text-align and see that working for the same tags.

2. Is there any way to push content further to the right for md+ view-ports - without dabbling with sidebar and main content individually? I tried changing .main, .home, .page but either see margin misalignments.

I am not a good designer - sorry if this sounds silly.

**Comment by MunifTanjim** [comment]
I'm not 100% sure about what you are trying to acheive, but maybe something like this?

```css
@media screen and (min-width: 920px) {
  .main-menu > div {
    justify-content: flex-end;
  }
}
```

**Comment by prashanth1k** [comment]
Thank you - that worked well.

I could not do something similar for all content (pt #2 - push all content to the middle of the screen). Any suggestions there?

**Comment by MunifTanjim** [comment]
Probably this:

```css
.site {
  max-width: 1040px;
  margin-left: auto;
  margin-right: auto;
}

@media screen and (min-width: 920px) {
  .sidebar {
    left: auto;
  }
}
```

But can't promise it'll work perfectly. :thinking:
