### ISSUE TITLE
Using mounts module breaks the theme

### ISSUE THREAD

**Issue by lobopraveen** [MunifTanjim/minimo#290]
### Steps to reproduce

1. Clone this repo `git clone https://github.com/MunifTanjim/minimo.git`
1. `cd minimo/exampleSite`
1. Edit the config file to point the theme to minimo theme and add mounts module as shown below
```toml
theme = "../../../minimo"

[module]
  [[module.mounts]]
    source = "public"
    target = "static"
```
4. `hugo server` renders the site properly; however, if you just build the site using `hugo`, all the files under `public/assets/` are zero byte files. Somehow the files are getting copied over from the theme's static directory to the publish directory (public) as zero byte files. 

Just to make sure that this not an issue with Hugo and the mounts module usage as shown above, I grabbed [the second theme](https://github.com/jakewies/hugo-theme-codex) from Hugo themes collection and added the mounts module exactly as shown above and the theme's CSS and JS files were copied properly. I'm thinking this could be something to do with the minimo theme.
