### ISSUE TITLE
When changing taxonomy name icon disappear

### ISSUE THREAD

**Issue by matrixik** [MunifTanjim/minimo#40]
When changing taxonomy name its icon disappear in post

```toml
[taxonomies]
author = "autorzy"
category = "ketegorie"
tag = "tags"
```
In post front matter:
```toml
+++
categories = [
  "Bez kategorii"
]
tags = ["otagować"]
+++
```

Test post: https://www.dobek.pro/2017/10/test/ (no icon near `Bez kategorii`)
I think issue could be here:
https://github.com/MunifTanjim/minimo/blob/master/layouts/partials/svg/icons.html#L2-L6

BTW. I still see English word "Category" on https://www.dobek.pro/ketegorie/ but did not have time to investigate.
