### ISSUE TITLE
Enhance Polish translation

### ISSUE THREAD

**Issue by MunifTanjim** [MunifTanjim/minimo#45]
Turns out, `go-i18n` supports `one`, `few`, `many` & `other` keys in translation files like this:

```toml
[stringID]
one = ""
few = ""
many = ""
other = ""
```

Reference: gohugoio/hugo#3947

We will have to change the translation strings with the key `one` to also include they keys `few` & `many` in [**`/i18n/pl.toml`**](https://github.com/MunifTanjim/minimo/blob/19319054b853d3dc73d64d062ab52f228675b089/i18n/pl.toml)
