### ISSUE TITLE
What is the proper way to modify scss variables in minimo while using it as a submodule?

### ISSUE THREAD

**Issue by mozrila** [MunifTanjim/minimo#62]
Is it most proper to fork it and have my own version where I periodically pull in changes?

Is there anyway to specify a custom scss file that get compiled with the theme to override things like the site maximum width?

Thanks

**Comment by MunifTanjim** [comment]
If you want to add custom css to override the default ones, you can use the **`customCSS`** option in the `config.toml` file. For example, this is the part you need to override via customCSS file for changing the maximum width:

```css
.comments-container #disqus_thread,
.entry-content, .entry-cover, .entry-cover figcaption,
.entry-footer, .entry-nav, .entry-toc,
.footer, .header, .home-sections, .list, .pagination,
.term-cloud {
    width:100%; max-width:740px; padding-left:20px; padding-right:20px;
}
```
But if you need to add you own custom SCSS file then, yeah, it's better to fork it and maintain your own version. All the SCSS files are stored in the **`/src/stylesheets`** folder.
