### ISSUE TITLE
How to make miscellaneous changes

### ISSUE THREAD

**Issue by Fastidious** [MunifTanjim/minimo#64]
Hi there! Thanks for the theme, it is simple, clean, and fast. I love it!

I would like to change:
* Fonts
* Links (show underline, colours, etc)

What would be the best way to do so?

**Comment by MunifTanjim** [comment]
- Create a CSS file in your site's **`/static/`** directory (e.g. `custom.css`).
- Add your custom CSS file's path (relative to **`/static/`** directory) to the, **`customCSS`** array option under **`[params.assets]`** section of your **`config.toml`** file (e.g. `customCSS = ["custom.css"]`).
- Now, you can override theme's default CSS from your `custom.css` file.

For example, you can override the theme's fonts by modifying the following CSS and add them to your `custom.css` file:

```css
body, button, input, select, textarea {
    font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen-Sans, Ubuntu, Cantarell, Helvetica Neue, Siyam Rupali, sans-serif;
}

.title, h1, h2, h3, h4, h5, h6 {
    font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen-Sans, Ubuntu, Cantarell, Helvetica Neue, Siyam Rupali, sans-serif;
}
```
