### ISSUE TITLE
Build error after upgrading to 2.0 - params.widget 

### ISSUE THREAD

**Issue by kmuncie** [MunifTanjim/minimo#93]
`Building sites … ERROR 2018/02/10 12:01:55 Error while rendering "home" in "": template: theme/index.html:10:11: executing "theme/index.html" at <len .Site.Params.wid...>: error calling len: len of untyped nil`

Seems like anyone upgrading from 1.X to 2.0 must add `[params.widgets]` to their config.toml in order for the site to build.  Correct me if I am wrong, is this the only breaking change for current users to 2.0? May be good to have an upgrade guide or something to specifically call out this breaking change for current users. 

The following is taken from the example config.toml -
```toml
[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","taxonomy_cloud"]
```
